### PR TITLE
Fix file summary switch

### LINKED ISSUE #55: hide/show summary button sets wrong url
clicking the + sign next to the "files changed" sets the url incorrectly (logic is backwards). 

When you first load the html file, the "+" sign is visible and the files changed are hidden.

but when you click it, it sets the URL to diff.html#d2h-hide-2t9. Clicking the (now changed to) minus sign, sets the URL to diff.html#d2h-show-w29. so, this seems backwards. clicking show should set the URL to a "show" status, and visa versa.

while we're on this topic..is it possible for you to change the +/- sign to something more obvious, like "show/hide", or "show files/hide files"?

i ask because the + sign is rather obscure and i'm using this for people who aren't as tech savvy, so a tiny '+' sign would probably largely go unnoticed.

### PR DESCRIPTION
**Pull request by rtfpessoa**
Fixes #55 

To perform this fix I decided to start diff2html-ui js module to simplify the html dynamic changes highlight or animations.

This is still a very simple idea and the code is very basic.

Not sure if I should use jQuery for this or just plain js like I did. Any suggestions?

### CODE REVIEW

File: js/diff2html-ui.js [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+ *
+ */
+
+var Diff2HtmlUI = (function() {
+
+  var diffJson = null;
+  var defaultTarget = "body";
+
+  function Diff2HtmlUI(config) {
+    config = config || {};
```
Comment (rtfpessoa) [inline js/diff2html-ui.js]: Codacy Issue found: [Assignment to function parameter 'config'.](https://www.codacy.com/app/Codacy/diff2html/file/1991855704/issues/source?bid=3025341&fileBranchId=3119681#l14)

File: js/diff2html-ui.js [hunk 2]
```diff
@@ -0,0 +1,103 @@
+/*
+ *
+ * Diff to HTML (diff2html-ui.js)
+ * Author: rtfpessoa
+ *
+ */
+
+var Diff2HtmlUI = (function() {
```
Comment (rtfpessoa) [inline js/diff2html-ui.js]: Codacy Issue found: ["Diff2HtmlUI" is defined but never used](https://www.codacy.com/app/Codacy/diff2html/file/1991855704/issues/source?bid=3025341&fileBranchId=3119681#l8)

File: js/diff2html-ui.js [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+    var that = this;
+
+    // collect all the file extensions in the json
+    var allFileLanguages = diffJson.map(function(line) {
+      return line.language;
+    });
+
+    // remove duplicated languages
+    var distinctLanguages = allFileLanguages.filter(function(v, i) {
+      return allFileLanguages.indexOf(v) == i;
```
Comment (rtfpessoa) [inline js/diff2html-ui.js]: Codacy Issue found: [Expected '===' and instead saw '=='.](https://www.codacy.com/app/Codacy/diff2html/file/1991855704/issues/source?bid=3025341&fileBranchId=3119681#l76)

File: js/diff2html-ui.js [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+ * Author: rtfpessoa
+ *
+ */
+
+var Diff2HtmlUI = (function() {
+
+  var diffJson = null;
+  var defaultTarget = "body";
+
+  function Diff2HtmlUI(config) {
```
Comment (rtfpessoa) [inline js/diff2html-ui.js]: Codacy Issue found: ["Diff2HtmlUI" is already declared in the upper scope.](https://www.codacy.com/app/Codacy/diff2html/file/1991855704/issues/source?bid=3025341&fileBranchId=3119681#l13)

File: dist/diff2html-ui.js [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+
+    if (config.diff) {
+      diffJson = Diff2Html.getJsonFromDiff(config.diff);
+    } else if (config.json) {
+      diffJson = config.json;
+    }
+  }
+
+  Diff2HtmlUI.prototype.draw = function(targetId, config) {
+    var that = this;
```
Comment (pbu88) [inline dist/diff2html-ui.js]: I don't think `var that = this;` is necessary here, because there are no scope changes so `this` will be the same in all the method instructions.

File: dist/diff2html-ui.js [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+      return allFileLanguages.indexOf(v) == i;
+    });
+
+    // pass the languages to the highlightjs plugin
+    hljs.configure({languages: distinctLanguages});
+
+
+    // collect all the code lines and execute the highlight on them
+    var codeLines = that._getTarget(targetId).getElementsByClassName("d2h-code-line-ctn");
+    [].forEach.call(codeLines, function(line) {
```
Comment (pbu88) [inline dist/diff2html-ui.js]: Wouldn't this be the same as `codeLines.each(function(line)) {` or am I missing something?

File: js/diff2html-ui.js [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+
+    if (config.diff) {
+      diffJson = Diff2Html.getJsonFromDiff(config.diff);
+    } else if (config.json) {
+      diffJson = config.json;
+    }
+  }
+
+  Diff2HtmlUI.prototype.draw = function(targetId, config) {
+    var that = this;
```
Comment (pbu88) [inline js/diff2html-ui.js]: I don't think `var that = this;` is necessary here because there are no scope changes in the method.

File: js/diff2html-ui.js [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+      return allFileLanguages.indexOf(v) == i;
+    });
+
+    // pass the languages to the highlightjs plugin
+    hljs.configure({languages: distinctLanguages});
+
+
+    // collect all the code lines and execute the highlight on them
+    var codeLines = that._getTarget(targetId).getElementsByClassName("d2h-code-line-ctn");
+    [].forEach.call(codeLines, function(line) {
```
Comment (pbu88) [inline js/diff2html-ui.js]: Isn't this the same as `codeLines.each(function(line) {` or am I missing something?

**Comment by pbu88** [comment]
Looks good. If everything can be accomplish without jQuery maybe is not worth it to include it, but I don't see any harm to include it using a CDN.

File: js/diff2html-ui.js (hunk 8 above)
Comment (rtfpessoa) [inline js/diff2html-ui.js]: The return of `getElementsByClassName` is some weird collection that you cannot map directly.
At least I do not know how to.
That was the best way I found.

File: src/ui/js/diff2html-ui.js [hunk 9]
```diff
@@ -0,0 +1,99 @@
...
+    var $codeLines = $target.find(".d2h-code-line-ctn");
+    $codeLines.map(function(i, line) {
+      hljs.highlightBlock(line);
+    });
+  };
+
+  Diff2HtmlUI.prototype._getTarget = function(targetId) {
+    var $target;
+    if (targetId) {
+      $target = $(targetId)
```
Comment (rtfpessoa) [inline src/ui/js/diff2html-ui.js]: Codacy Issue found: [Missing semicolon.](https://www.codacy.com/app/Codacy/diff2html/file/1992937605/issues/source?bid=3025341&fileBranchId=3119681#l86)
