### PR TITLE
Fix parsing on Windows

### LINKED ISSUE #57: Fix diff parsing on windows line ending
Copied from [https://github.com/rtfpessoa/diff2html-cli/issues/16](https://github.com/rtfpessoa/diff2html-cli/issues/16)

when the diff diff2html-cli is given, has CRLF line endings, the generator will generate a valid html file, but it will act as if the source diff was empty.

obviously, this isn't ideal on windows -- especially when everything is so hard coded (cmd, powershell) to always output \r\n.

i'm not sure how fixable this is for you, or if it touches the entire code base (hope not). presently i'm running dos2unix on the diffs i create from hg, but of course that is a real hack and has its own pitfalls.

### PR DESCRIPTION
**Pull request by rtfpessoa**
Fixes #57 

Replace windows EOL by Unix EOL

It should work for `\r\n`, `\r` and `\n`.

@pbu88 what do you think?

### CODE REVIEW

File: src/diff-parser.js [hunk 1]
```diff
@@ -124,6 +124,7 @@
 
     var diffLines =
       diffInput.replace(/\\ No newline at end of file/g, '')
+        .replace(/\r\n?/g, '\n')
```
Comment (pbu88) [inline src/diff-parser.js]: Why the quote sing is in the `\n`? I thought it should be in the `\r`.

Comment (rtfpessoa) [inline src/diff-parser.js]: As far as I know there are three types of EOLs. Linux and OS X use LF (`\n`), Windows uses CRLF (`\r\n`) and old OS X used (`\r`). This way we can parse them all since we are making the CR optional and always converting to LF.

Comment (pbu88) [inline src/diff-parser.js]: Oh I see, didn't know about the old OS X variant.

File: test/diff-parser-tests.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+      var result = Diff2Html.getJsonFromDiff(diff);
+      var file1 = result[0];
+      assert.equal(1, result.length);
+      assert.equal(1, file1.addedLines);
+      assert.equal(1, file1.deletedLines);
+      assert.equal('sample', file1.oldName);
+      assert.equal('sample', file1.newName);
+      assert.equal(1, file1.blocks.length);
+    });
+
```
Comment (pbu88) [inline test/diff-parser-tests.js]: We might want to add the tests cases for mixing line ends `\r\n` and `\n` in the same file and for the old OS X version `\r` only.

Comment (rtfpessoa) [inline test/diff-parser-tests.js]: Ups, seems like I deleted to CR version.
It is possible to have mixed versions?
Still it should handle them fine. I will the tests.

**Comment by rtfpessoa** [comment]
@pbu88 any other suggestions?

**Comment by pbu88** [comment]
Looks good :) I really think that with this small fix (replacing EOLs with a regex) it should be enough. Time will tell. Thanks!
